releasenotes:
  sections:
  - title: "Headliners"
    emoji: ":star:"
    group: "highlights"
  - title: "New Features"
    emoji: ":sparkles:"
    labels: [ "enhancement" ]
  - title: "Bugs Fixed"
    emoji: ":beetle:"
    labels: [ "bug" ]
  - title: "Automation"
    emoji: ":robot:"
    labels: [ "automation" ]